apiVersion: v1
kind: Template
metadata:
  name: pv-basic
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: apps/dockerfile-basic
      git:
        uri: https://github.com/nekop/openshift-sandbox
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhel-tools:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    selector:
      name: ${APPLICATION_NAME}
    replicas: 1
    template:
      metadata:
        labels:
          name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 2000
          volumeMounts:
          - mountPath: /pv
            name: ${APPLICATION_NAME}
        volumes:
        - name: ${APPLICATION_NAME}
          persistentVolumeClaim:
            claimName: ${APPLICATION_NAME}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rhel-tools
  spec:
    dockerImageRepository: registry.access.redhat.com/rhel7/rhel-tools
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 2000-tcp
      port: 2000
      protocol: TCP
      targetPort: 2000
    selector:
      deploymentconfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    resources:
      requests:
        storage: 16Mi
parameters:
- name: APPLICATION_NAME
  required: true
  value: pv-basic
